### ISSUE TITLE
Improper pluralization of octopus/stadium

### ISSUE THREAD

**Issue by CSobol** [blakeembrey/pluralize#100]
Pluralization of octopus should be either "Octopodes" for the greek style, or "Octopuses" for the american style. Octopi is incorrect, though comonly misused.
https://english.stackexchange.com/questions/270/what-is-the-correct-plural-of-octopus/271

Similarly, plural for "stadium" should be "stadia".

**Comment by blakeembrey** [comment]
Seems like it should be stadiums and not stadia though? https://english.stackexchange.com/questions/29060/what-is-the-correct-plural-of-stadium

Feel free to submit a PR to change "octopuses".
