### ISSUE TITLE
Using in ES2015 project

### ISSUE THREAD

**Issue by ksnyde** [blakeembrey/pluralize#102]
I can transpile Pluralize into an ES2015 library I've created but when I use `rollup` to transpile to CJS and UMD it gives me the warning that:

> 'plural' is not exported by 'node_modules/pluralize/pluralize.js'

Modules isn't a complete dark art to me but there's still a lot to learn. I just wondered if there was something about the export method that's been used in this library that would prevent me from doing this transpilation.

**Comment by wopian** [comment]
You need to add it to your Rollup's global configuration. https://rollupjs.org/guide/en#output-globals-g-globals

```js
global = {
  pluralize: 'plural'
}
```

**Comment by ksnyde** [comment]
many thanks!
