### ISSUE TITLE
Incorrect singular of 'databases' -> 'databasis' (any containing ^bases suffix)

### ISSUE THREAD

**Issue by vpiskunov** [blakeembrey/pluralize#104]
Any clue where the issue is arising from? Happy to fix this, but a pointer would be good

**Comment by vpiskunov** [comment]
Seems fixed by `pluralize.addSingularRule(/bases$/i, 'base')` but curious where this came from to see if any other words are affected.

**Comment by blakeembrey** [comment]
Looks like an issue with singularizing words ending in "bases" because of https://www.merriam-webster.com/dictionary/basis.

**Comment by blakeembrey** [comment]
Fixed with https://github.com/blakeembrey/pluralize/commit/c46c6af6998a11c92212feea004f67cb2e76124c since it doesn't really make sense to support the less common usage of "basis" here. The singular to plural will work, but the conflict going back will work as expected.
