### ISSUE TITLE
Polymer JS import not working on Chrome or Safari / Partially on Firefox

### ISSUE THREAD

**Issue by boosey** [blakeembrey/pluralize#105]
I am writing a simple app in Polymer. When I import pluralize I get partial functionality on Firefox but no functionality on Chrome or Safari.

I am using the following line to import into my app:
`import '../node_modules/pluralize/pluralize.js'`

I've also tried other variants with the same or worse results:
`import pluralize from 'pluralize'`
 `const pluralize = require('../node_modules/pluralize/pluralize.js')`

The import fails on Chrome with the error:
> TypeError: Cannot set property 'pluralize' of undefined

The failing line in pluralize.js is:
   ` root.pluralize = pluralize();`
which is the fallback case for exporting the function.  `root` is undefined.

On Firefox is doesn't fail, yet I must reference by using from the window object:
`window.pluralize.isPlural(thing) ? "are" : "is"`

How do I get the `pluralize` object imported and initialized in my Polymer application.

**Comment by blakeembrey** [comment]
I don’t know. What does Polymer do that changes something that has worked for five years without any problem? If you have a sample project I can take a look for you. Or docs I can review about the import behaviour of Polymer.

**Comment by boosey** [comment]
Here is the information about Polymer's use of imports and modules. 
[https://www.polymer-project.org/3.0/docs/es6](url)

I also have modified the pluralize.js file:
Removed lines 1 - 17
Removed lines 489 - 490
Appended `export default pluralize;` to the end of file

I import into my code using:
`import pluralize from 'pluralize'`

This works in all three browsers.
I would have tried to modify lines 1 - 17 to make my import work, but my javascript skills aren't good enough to grasp the purpose of those lines.

**Comment by blakeembrey** [comment]
Thanks. That’s just ES6 modules. Unfortunately I can’t adopt ES6 modules right now since the support is spotty and it’s backward incompatible with other module systems. Do you know if Polymer supports AMD, CommonJS or regular globals? That’s what the lines in the code are for.

**Comment by blakeembrey** [comment]
Based on https://www.polymer-project.org/blog/2018-02-26-3.0-preview-paths-and-names, if you imported directly from the module name instead of the relative path, it’s should “just work”.
