### ISSUE TITLE
Words ending with "ia" are not pluralized correctedly

### ISSUE THREAD

**Issue by zoldello** [blakeembrey/pluralize#110]
These words are not getting pluralized: "Russia",  "Nigeria" and "Liberia" all end with "s" rather than "ns". The "euphoria" is both is singular and plural form.

**Comment by ImLiam** [comment]
Unless I'm mistaken, the suggestions you've made here don't seem valid at all.

The singular "Russia" means the country, while the proposed "Russians" means the people of Russia - which is a completely different meaning.

The "problematic" words here are all names that can't be pluralised in such a way.

**Comment by timkrins** [comment]
Yep - sorry, every one of your points seem invalid.

Russia => Russias (correct, but strange - as it is strange to have a plural of an individual country)
Nigeria => Nigerias (correct, but strange, as above)
Liberia => Liberias (correct, but strange, as above)
Euphoria => Euphorias (Euphoria is _not_ the singular and plural)

**Comment by blakeembrey** [comment]
Thanks @timkrins and @imliam. Closing for now. You can override this behavior in your own instance 😄
