### ISSUE TITLE
Add zero rule

### ISSUE THREAD

**Issue by l0gicgate** [blakeembrey/pluralize#112]
I was wondering if it's possible to substitute `0` for a word like `No`

Example:
`pluralize.addZeroRule('test', 'no')` would yield `No tests` instead of `0 tests`

**Comment by blakeembrey** [comment]
I'd suggest doing a wrapper function yourself, e.g. `(word, num) => num === 0 ? `No ${pluralize.plural(word)}` : pluralize(word, num, true)`.

**Comment by l0gicgate** [comment]
Thank you @blakeembrey
