### ISSUE TITLE
Pluralize trailing underscore: What is the expected behavior for pluralize('frog_')?

### ISSUE THREAD

**Issue by shanebdavis** [blakeembrey/pluralize#121]
What is the correct behavior for pluralizing words that end in non-word characters like a trailing underscore? 

I recently changed my hack-of-a-pluralize code (just add "s"!) to this awesome library. However, I had one surprise result. When pluralizing "frog_" I ended up with "frog_S". Why the upper-case "S"? Shouldn't it at least be lower-case?

Thinking about it, I think the best behavior would be to remove any non-word characters from the end first, then pluralize, then re-attach the removed characters.

Examples:

```
pluralize("frog_")
// currently outputs > "frog_S" -- probably wrong
// should probably output > "frog_s" or "frogs_" 
```

The "remove then reattach" method makes more sense when we have non-trivial pluralization:

```
pluralize("person_")
// currently outputs > "person_S"
// should probably output > "person_s" or "people_"
```

---

Why do I care? My parser-generator (npm caffeine-eight) automatically generates pluralized names from client-provided rule-names. Sometimes those rule-names have trailing underscores. This turns out to be a useful pattern for expressing if a rule consumes whitespace - something that must be done manually with parsing-expression-grammar parsers.

**Comment by blakeembrey** [comment]
This sounds out of scope of this projects purpose. You should probably do your proposed removing on non-work characters in your own project and then add them back afterwards. I don't think it's as easy as it seems and definitely subjective (as the "S" you've pointed out) so I'd prefer to keep it out of this project.

**Comment by shanebdavis** [comment]
I understand wanting to keep things generally applicable, but I’d still like to have some definition for how “pluralize” handles these situations - however it does it.

**Comment by blakeembrey** [comment]
Which situations? It doesn't handle them at all. It just fell back on appending an `s` because no other rules matched. As for the upper case, that's also because of the `_` there, see https://github.com/blakeembrey/pluralize/blob/master/pluralize.js#L48-L62 (`word = _, token = s`).

**Comment by shanebdavis** [comment]
Interesting. Since uppercase “_” is the same, it thinks it should uppercase
the ”s.”

Thanks for replying, and thanks for the great library!

**Comment by blakeembrey** [comment]
Pretty much, it's not very sophisticated and I'll probably relegate this logic to a separate method in the future - definitely a lot of confusing questions from how it works.
