### ISSUE TITLE
whisky vs whiskey, when from plural to singular 

### ISSUE THREAD

**Issue by AndreiMotinga** [blakeembrey/pluralize#123]
```
    console.log("whisky", pluralize("whisky")) // whisky whiskies
    console.log("whiskey", pluralize("whiskey")) // whiskey whiskies

    console.log("whiskies", pluralize.singular("whiskies")) // whiskies whiskey.
    ~console.log("whiskeys", pluralize.singular("whiskey")) // whiskeys whiskey~
    EDIT: made a mistake here ^^^. meant this 
    console.log("whiskeys", pluralize.singular("whiskeys")) // whiskeys whiskey
```

so `whisky` to plural =>  `whiskies` and back to singular and we have new word => `whiskey`

**Comment by blakeembrey** [comment]
What’s the issue here? Are you saying the singular word is incorrect, i.e. it’s not whiskey? There’s no possible way you can singularize to two different words magically.

**Comment by AndreiMotinga** [comment]
@blakeembrey, I think `pluralize.singular("whiskies"))` should return `whisky`, not `whiskey`

**Comment by blakeembrey** [comment]
Can you reference an authoritative source? Without that this sounds subjective given https://www.merriam-webster.com/dictionary/whisky even sends you to whiskey. The iOS keyboard also suggests it over whisky. It’s totally possible this module could create an en-UK version or other localizations, it seems like it might be that. This module is purely en-US.

**Comment by AndreiMotinga** [comment]
@blakeembrey, I'm only basing this on my limited knowledge of English (it's my second language),  but still. 

https://www.google.com/search?ei=2hjCXJ6GFI-t5wLAm4Rg&q=whisky+plural&oq=whisky+plural&gs_l=psy-ab.1.0.0l2j0i22i30l8.44315.45937..47624...0.0..0.376.1584.14j1j0j1......0....1..gws-wiz.......0i71j35i39j0i131j0i20i263.CC49mJyyEMI

> Most Irish whiskeys are distilled from barley that's dried in kilns. But our blog is about language, not booze. As you've noticed, there's another difference between these libations—the spelling. In Scotland, they make Scotch “whisky” (plural “whiskies”), but in Ireland they make Irish “whiskey” (plural “whiskeys”).

https://www.grammarphobia.com/blog/2012/12/whiskey-whisky.html


Historically, they say, whisky vs whisky has to do with some countries trying to distinguish their 'original', 'quality' product from other liqueurs that weren't true whiskey at the beginning of the 20th century. It's not really the case anymore. 

Anyhow, just following English rules
`whisky` ends with an `ky` so plural should be `whiskies`, while 
`whiskey` ends with `ey`, therefore should be `whiskeys`. Aren't they?

what happens now is we have a word that we can pluralize, 
  but we get a different word when transforming it back to singular. 

here's output from rails console. 

```
irb(main):018:0> "whisky".pluralize
"whiskies"
irb(main):019:0> "whiskies".singularize
"whisky"
irb(main):020:0> "whiskey".pluralize
"whiskeys"
irb(main):021:0> "whiskeys".singularize
"whiskey"
irb(main):022:0>
```

**Comment by blakeembrey** [comment]
Ok, so to clarify, you’re saying the pluralization is incorrect here.
