### ISSUE TITLE
Installation with npm includes older code

### ISSUE THREAD

**Issue by ethannam** [blakeembrey/pluralize#125]
After executing `npm install pluralize --save`, `pluralize('passerby')` outputs "passerbies".

Your GitHub repo actually already accounts for this irregular rule (passerby should be passersby). I see the rule on line 321 in pluralize.js. But my local version is missing ['passerby', 'passersby'] in the array.

Any way the updated version can be published to npm?

**Comment by blakeembrey** [comment]
Published as 8.0.
