### ISSUE TITLE
Nested Rules

### ISSUE THREAD

**Issue by sebaveg** [blakeembrey/pluralize#133]
Hi !

I would code this but not work:
```js
pluralize
  .addPluralRule(/r$/i, 'res')
  .addPluralRule(/ /g, '-')
```
So I code this:
```js
pluralize.addPluralRule(/r$/i, 'res')
pluralize.addPluralRule(/ /g, '-')
```

**Can the object be returned for nested?**

**Comment by blakeembrey** [comment]
It could be done if you wanted to submit a PR.

**Comment by blakeembrey** [comment]
Closing since void returns in methods are normal and making it a fluent API doesn't really improve anything for this package except increase size.
