### ISSUE TITLE
Are we going to support this on Java or Kotlin ?

### ISSUE THREAD

**Issue by abhayjatindoshi** [blakeembrey/pluralize#146]

**Comment by blakeembrey** [comment]
No, I will not be. You're welcome to do it.

**Comment by abhayjatindoshi** [comment]
I've tried converting JS to Java, and I'm almost done (https://github.com/encryptorcode/pluralize)
1. If it okay to have this open source under my github account. I'll make sure to mention this repository in my README. 
2. Also is it okay if I published it to [maven central](https://mvnrepository.com/repos/central) as its the npm for Java

@blakeembrey

**Comment by blakeembrey** [comment]
SGTM @abhayjatindoshi. One thing I might do in the coming months (always intended to do anyway) is publish the rules via JSON. Would that help you at all?

**Comment by abhayjatindoshi** [comment]
Yes, that'd be really great. I'll be able to write a bot to keep the rules in both the repos in sync.
and thanks @blakeembrey. I'll go ahead and finish my README by Sunday.
