### ISSUE TITLE
Plural of "do"/"does"

### ISSUE THREAD

**Issue by Noitidart** [blakeembrey/pluralize#155]
I'm trying to pluralize "they do not show up" however struggling.

First report is regarding "they" over here - #154 

Second part is I can't get "does" to singular to "do":

pluralize('does', 1) = doe
pluralize('do', 2) = dos

**Comment by blakeembrey** [comment]
Do and does aren't really in scope for this project. If you want to propose a solution to handling verbs I can definitely give it a shot or accept a PR, but right now the project is scoped to nouns which have plurals.

**Comment by Noitidart** [comment]
Oh no problem brother. I didn't realize it was different grammar. Closing. Thanks for the quick comment!
