### ISSUE TITLE
Uncountable rules are not ignored when singularized.

### ISSUE THREAD

**Issue by DylanPiercey** [blakeembrey/pluralize#20]
"series" is an uncountable word.

However:
```javascript
pluralize("series", 1) // -> "sery"
```

I think uncountable words should be ignored when singularized as well as pluralized.

**Comment by blakeembrey** [comment]
@DylanPiercey This is how it works currently, and I'm pretty sure the initial commit included `series` handling. What version are you using?

**Comment by DylanPiercey** [comment]
Seems to be working now - must have been my fault somewhere!

Thanks for your response.
