### ISSUE TITLE
Yous

### ISSUE THREAD

**Issue by 1j01** [blakeembrey/pluralize#21]
```js
pluralize("you") // "yous"
```
While "yous" (or "youse") may be considered a word by some dictionaries, the accepted correct pluralization of "you" is "you".

**Comment by blakeembrey** [comment]
@1j01 You're right. We maintain a manual uncountable and odd cases list, but it's not currently there. That said, I'm not sure whether the plural would be "they". Thoughts?

**Comment by blakeembrey** [comment]
Ok, read some interesting stuff and "you" works. I'll add a manual rule for singular "thou" to "you" too, and leave "you" as "you".
