### ISSUE TITLE
Olife

### ISSUE THREAD

**Issue by 1j01** [blakeembrey/pluralize#22]
```js
pluralize("olives", 1) // "olife" (should be "olive")
```
Some words to be added to [this rule](https://github.com/blakeembrey/pluralize/blob/5a0706915dcba9231e86d6c0a863a3783d995b8d/pluralize.js#L330) include olive, adhesive, explosive and maybe some others from [this list](http://www.onelook.com/?w=*ive&posfilter=cn)

**Comment by blakeembrey** [comment]
Thanks :+1:

**Comment by 1j01** [comment]
Thanks for the module :smiley_cat:

**Comment by blakeembrey** [comment]
@1j01 I've refactored it to prefer "ive" -> "ives" with exceptions the other way. Would you mind taking a second to review the changes and make sure it makes sense?

**Comment by 1j01** [comment]
Looks good to me
