### ISSUE TITLE
Capitalization breaking uncountable rule application

### ISSUE THREAD

**Issue by kinergy** [blakeembrey/pluralize#29]
`pluralize.plural('staff')` returns `staff`
`pluralize.plural('Staff')` returns `Staffs`

**Comment by blakeembrey** [comment]
@kinergy Confirmed, thanks for the report. I'll release a new minor tonight with the patch.

**Comment by blakeembrey** [comment]
@kinergy Release with `v1.2.0` :+1: Thanks!

**Comment by kinergy** [comment]
Thanks for the quick-turn!
