### ISSUE TITLE
pluralize('s',1)  === ''

### ISSUE THREAD

**Issue by carney520** [blakeembrey/pluralize#36]

**Comment by blakeembrey** [comment]
What is the expected behavior?

**Comment by carney520** [comment]
why singular “s“ equals to ””. In my eyes it should be "s".

**Comment by blakeembrey** [comment]
Yes, probably. However, I won't be making the change as it breaks current behaviour. Currently, it's going through singularization or pluralization based on the count. It's simple RegExp based logic, so it thinks "s" is a plural and "singularizes" it.
