### ISSUE TITLE
Add new rules

### ISSUE THREAD

**Issue by Santinell** [blakeembrey/pluralize#37]
What do you think about add rules from another library?
For example:
https://github.com/dreamerslab/node.inflection/blob/master/lib/inflection.js

If you agree, I can make PR

**Comment by blakeembrey** [comment]
What would you add? It's not about rules, I'm sure I cover more than that because I've checked in the past. Is there something missing? You're welcome to submit a PR, just make sure there are tests for the new cases.

**Comment by blakeembrey** [comment]
Closing without any response.
