### ISSUE TITLE
incorrect results for words ending '-ties'

### ISSUE THREAD

**Issue by simonwiles** [blakeembrey/pluralize#41]
Words like "varieties", "niceties" etc. are incorrectly singularized:

    pluralize('variety', 2) //=> "varieties"
    pluralize('varieties', 1) //=> "varietie"

because they match the rule `[ /(^[pl]|zomb|^(?:neck)?t|[aeo][lt]|cut)ies$/i, "$1ie" ]`.

Judging from the tests, the `[aeo]` part in this rule is to protect the "-ie" ending on the words "floatie" and "goalie" (the former of which is especially questionable).

**Comment by blakeembrey** [comment]
Would you be interested in briefly reviewing https://github.com/blakeembrey/pluralize/pull/42 and seeing if I missed anything? I've made that list a more hard-coded list of escapes.

**Comment by simonwiles** [comment]
Thanks Blake, this looks comprehensive.  I'd say go ahead and merge it.  Cheers!
