### ISSUE TITLE
Change case unexpectedly

### ISSUE THREAD

**Issue by tylerlong** [blakeembrey/pluralize#43]
```
> const pluralize = require('pluralize');
undefined
> s = 'RingOutRequestTo'
'RingOutRequestTo'
> pluralize(s, 1);
'RingOutRequestto'
```

The final result should be `RingOutRequestTo` instead of `RingOutRequestto`.

**Comment by blakeembrey** [comment]
It's really impossible to do what you suggest. This is a generic module for pluralising words, not camel cased variables. As a result, you will definitely end up with this breaking - the module does not know this is actually four words. What do you expect should happen?

I would suggest you split it into words before pluralising it.

**Comment by blakeembrey** [comment]
I've altered the behaviour with https://github.com/blakeembrey/pluralize/commit/90d82f88428f057c4b7a1d46aa38fc7c44d2d869, but I'll hold of releasing it as 4.0 until something more meaningful also exists in the release. Keep in mind, your example still can and will break on different word matches and replacements.

**Comment by tylerlong** [comment]
@blakeembrey the library is used to pluralize and singularize any word. It should not change the case.  I know in the example I gave it's not a single word. But still it shouldn't change the case.

**Comment by blakeembrey** [comment]
And how do you expect that's even possible? You can submit a PR, but it'd be practically magic. For instance. Your example is an extremely trivial, what about when you try to do something obscure where characters are actually replaced? What do you suggest the algorithm is there?

**Comment by blakeembrey** [comment]
In your above example, it matched against the regexp `/(x|ch|ss|sh|zz|tto|go|cho|alias|[^aou]us|tlas|gas|(?:her|at|gr)o|ris)(?:es)?$/i`. This isn't a dictionary. It doesn't know that it's not a word. It's a small, naive algorithm based on replacements. As far as it's concerned, it matched a word and singularised it.

**Comment by blakeembrey** [comment]
The best solution I can think of is to try and mirror when existing characters that are the same. Going through one by one and making them match. But then, what does it mean for the rest of the characters that don't match? It's still possible if you're doing something like this that it won't guess the rest of the sequence of casing correctly or that it didn't even match the correct word and has replaced incorrectly to start with - as it already did.

**Comment by tylerlong** [comment]
Hi @blakeembrey thank you for the detailed explanation. I didn't know the implementation detail of this project. From an end user's point of view, it is weird if the plural is unchanged but the case is changed. I will spend more time to investigate after I finish the tasks on hand. For now I have a simple solution: If the final result only differs in case with the input, then use the input as final result. Does it make sense? I know things are more complicated than I think because you need to take care of every edge case. Again, I need more time to investigate. Thank you for the quick response. Appreciate!

**Comment by blakeembrey** [comment]
That's all the changes I did in the commit I mentioned above for now. As I mentioned though, is all it does it mask a bigger bug in your system that will manifest itself in unexpected ways and I don't recommend it.

**Comment by maxsalven** [comment]
Am not sure if this is directly related, but there are still some case related issues:
```javascript
pluralize.addIrregularRule('Flock of Sheep', 'Flocks of Sheep')
pluralize('Flock of Sheep') // = "Flocks of sheep"
```

I appreciate one should be pluralising 'flock' by itself in this specific case, but if you can look beyond my contrived example, I still find the downcasing behaviour to be unexpected.

**Comment by blakeembrey** [comment]
Again, it's not possible to do what you want. If you think it is, feel free to submit a PR.

**Comment by blakeembrey** [comment]
It is related though, it's just not possible to do easily - for irregular rules, it could add a case-sensitive matching instead, but the useful of that is probably quite limited.

**Comment by blakeembrey** [comment]
Also, if what you want is to programatically pluralise in an application - this is probably the wrong use-case for you. You should probably be using something like https://github.com/sindresorhus/plur instead.
