### ISSUE TITLE
Update usage

### ISSUE THREAD

**Issue by geesen** [blakeembrey/pluralize#47]
The usage in readme says 
`pluralize.plural('singles', 1)`
to singularize a word. This seems not to work, since it gives me `singles`. 
After digging into the sources, it turns out to be
`pluralize.singular('singles')`

So, I think, the readme/usage is outdated?!

**Comment by blakeembrey** [comment]
Thanks, it would appear the README is incorrect. I'll update that now 😄 It's possible that I had attempted to document it using the primary API (which accepts "count") instead of the method API, but who knows - it was written a long time ago.
