### ISSUE TITLE
Need to pluralize multiple words in a string

### ISSUE THREAD

**Issue by bcowgill** [blakeembrey/pluralize#48]
0/no files include "cake" in their names.
1 file includes "cake" in its name.
2 files include "cake" in their names.

This could be written with multiple calls to pluralize but I think a template based string function would be better.

'[number/no] [pl:file] [!pl:includes] "cake" in [pl:its/their] [pl:name]'

Language.makePlural(
'[number] [pl:file] [!pl:includes] “cake” in [pl:its/their] [pl:name]'
, value
)

I need this for an application so will write one. If you want to include in your library let me know. Suggestions for alternate token/syntax welcome.

**Comment by blakeembrey** [comment]
I don't think this is suitable for this library. If you can write the template upfront, you would know the plurals already and you really shouldn't be using this library. You should just be writing switches in your template that selects a or b depending on count.
