### ISSUE TITLE
Question: use plural for zero?

### ISSUE THREAD

**Issue by evisong** [blakeembrey/pluralize#52]
Hi, 

Thanks for the lib, so happy to see he even recognizes Chinese characters. 

I'm running the following test and it passed:

```js
expect(pluralize('test', 0, true)).to.equal('0 tests');
```

But I'm curious that is it common to use plural for zero in English? (I'm not native English speaker)

Thanks.

**Comment by blakeembrey** [comment]
Yes, it is. It's a little odd, but in English zero is a plural. The only plural is one. You should be able to find plenty of references, but here's one that showed up when I searched: https://english.stackexchange.com/questions/38293/why-is-zero-followed-by-a-plural-noun. Hope that helps!
