### ISSUE TITLE
Pluralize negative values

### ISSUE THREAD

**Issue by havgry** [blakeembrey/pluralize#59]
Currently `pluralize('test', -1)` returns `tests` but the singular form would make more sense. Use cases include `point`, `coin`,  etc. What do you think?

**Comment by PeterTeng** [comment]
My rule is basically pluralizing when number is not 1

Check this out!
https://meta.stackexchange.com/questions/165244/is-negative-one-plural

```javascript
pluralize('test', 1)
// => test
pluralize('test', 0.5)
// => tests
pluralize('test', -0.5)
// => tests
pluralize('test', -1)
// => tests
```

I also think this should be customized by each use in your application.

Just an example here 👇 

```javascript
import pluralizePack from 'thisPackage';

export function pluralize(singular, count, showCount = false) {
  const word = String(singular);
  if (count === -1 && singular === 'test') {
    return word;
  }
  if (count === -1 && singular === 'point') {
    return word;
  }
        .
        .
        .
  return pluralizePack(singular, count, showCount);
}
```

**Comment by blakeembrey** [comment]
It seems reasonable to leave it how it is today. I'd recommend writing your own function for your behaviour today, it's pretty small based on https://github.com/blakeembrey/pluralize/blob/3da4a24ab94790b239545c6eb21f0f63cdc0ed09/pluralize.js#L165-L168.

**Comment by havgry** [comment]
Yes, it's easy to write a wrapper but I wanted to point out a case that wasn't being handled by the module but probably should. The answer seemed so obvious to me that it didn't even occur to me to google it. It indeed seems like there isn't a strong concensus on whether `-1` should be singularized and as such it makes sense to leave it as is.

**Comment by blakeembrey** [comment]
@havgry I agree. I would have also though that -1 was singular before reading. But since it's a little subjective and the existing behaviour is already there, figured it's reasonable to keep current expectations. Maybe we can add a note on the README?
