### ISSUE TITLE
pluralize.singular('carnivorous')=='carnivorou'

### ISSUE THREAD

**Issue by caub** [blakeembrey/pluralize#60]
which is not great

**Comment by blakeembrey** [comment]
This seems like an uncountable, right? I definitely don't pretend to have a complete list of uncountable words, that might be impossible - but I'm happy to add it.

**Comment by blakeembrey** [comment]
Question: Is there any singular or plural words ending with "ous"?

**Comment by caub** [comment]
good point, all the terms ending with "ous" https://www.morewords.com/ends-with/ous/ are adjectives, and always with the same plural and singular

**Comment by blakeembrey** [comment]
In which case, it's a pretty easy addition to the "uncountables" list to catch `/ous$/`. Curious if I'm missing anything, but I'll make a PR and leave it for a bit in case someone else wants to jump in.

**Comment by caub** [comment]
ok, thanks

**Comment by caub** [comment]
`santa clau` too, is badly singulazized

**Comment by blakeembrey** [comment]
I don't intend to maintain a list of nouns and countables, it would continue growing forever.
