### ISSUE TITLE
Is it possible to pluralize more than one word

### ISSUE THREAD

**Issue by jmwither** [blakeembrey/pluralize#62]
As an example this would be cleaner;
pluralize('file has', 1, true) = 1 file has
pluralize('file has', 5, true) = 5 files have

than: 
pluralize('file', 1, true) + ' ' + pluralize('has', 1, false)  = 1 file has
pluralize('file', 5, true) + ' ' + pluralize('has', 5, false)  = 5 files have

**Comment by blakeembrey** [comment]
Not currently. But if you already know the words, why would you need this module? You can just put them in a ternary.

**Comment by blakeembrey** [comment]
I'm going to close this as won't fix for now. If someone has a proposal that would make this sort of thing possible, feel free to let me know. However, these two plural cases don't feel particularly joined and I don't have a way to properly solve this except doing them separately for now.
