### ISSUE TITLE
NPM Publish

### ISSUE THREAD

**Issue by benmarch** [blakeembrey/pluralize#68]
I'm excited to start using this library, but I need to use the `isPlural()` function from v5.1.0 which is not available in NPM (latest is 5.0.0). Would you mind publishing the latest to NPM, please?

Thanks!
Ben

**Comment by blakeembrey** [comment]
Install `6.0.0`?

**Comment by blakeembrey** [comment]
Also, it was released two hours before this issue: https://github.com/blakeembrey/pluralize/releases/tag/v6.0.0. See:

![image](https://user-images.githubusercontent.com/1088987/28344365-d2ebe9da-6bf0-11e7-9fc2-0d7a9d1e0ce2.png)

Are you running into some other issue or were you just looking at an outdated page? I don't tag releases on GitHub until after NPM publish usually, so it's odd you'd make this issue.

**Comment by wopian** [comment]
The `npm` package page (sometimes?) gets cached for a few hours - so could well have been displaying `5.0.0` as the latest instead of `5.1.0` at the time

**Comment by benmarch** [comment]
Sorry about that, it was indeed cached (I did run npm info just prior to opening the issue). I can see 6.0.0 now.

**Comment by blakeembrey** [comment]
Thanks @wopian. I've noticed the NPM web cache issue before, but never with package/info outdated. @benmarch are you perhaps using a different registry? Glad it's working now either way.

**Comment by benmarch** [comment]
@blakeembrey yes I was using my company's registry at the time, and it has a 24h cache period. I'll be sure to bypass it next time I run npm info. BTW I'm now using change-case as well, these are awesome libraries! Thank you!
