### ISSUE TITLE
Singularizing contractions and possessives?

### ISSUE THREAD

**Issue by Tyler-Murphy** [blakeembrey/pluralize#73]
Words like `it's` have the `s` after the apostrophe removed. What do you think of modifying the library to leave the `s` on if it follows an apostrophe?

```node
> singular("it's")
'it\''
```

**Comment by blakeembrey** [comment]
If you'd like to submit a PR and it doesn't impact any of the existing functionality negatively, go for it. However, I'd say this is outside the domain of `pluralize` - it doesn't and currently shouldn't handle things like acronyms or contractions. Is there a reason you're trying to use it on something that isn't supported?
