### ISSUE TITLE
Plural after a number is in upper rather than lower case

### ISSUE THREAD

**Issue by robwebset** [blakeembrey/pluralize#77]
First off - thank you for sharing this with everyone, a lovely little library for Node JS.

I have spotted that if you call pluralize with a string ending in a number then it always appends the "s" as upper case. For example:

pluralize.plural('Blank Application2');

will return 'Blank Application2S' rather than 'Blank Application2s' which I think would look nicer :)

Thanks
Rob

**Comment by blakeembrey** [comment]
Happy to accept a PR either reversing trying to detect "upper case" or making this behaviour pluginable. However, this is already a pretty undefined use-case - not sure if it should even be appending anything?

**Comment by robwebset** [comment]
Thanks, I've created pull request #82

**Comment by ispringer** [comment]
I am seeing a similar issue when the input string ends with a punctuation mark. For example, "Bugleweed (Arjuga)" is pluralized to "Bugleweed (Arjuga)S". I think in that case, it definitely makes the most sense to not do anything. Should I create a separate issue for the punctuation case or will #82 take care of it?

**Comment by blakeembrey** [comment]
@ispringer What would you want to happen in that case? It's not handled by https://github.com/blakeembrey/pluralize/pull/82 which just makes things lowercased instead.

**Comment by ispringer** [comment]
You could try to get fancy and pluralize both Bugleweed and Arjuga, but I think that might be too presumptuous. I would probably do nothing and just return the input as is.

**Comment by HosseinAgha** [comment]
@blakeembrey @robwebset this still happens in `v8.0.0`

**Comment by blakeembrey** [comment]
@HosseinAgha Works for me:

```js
> require('.').plural('Journals2')
'Journals2s'
```

**Comment by blakeembrey** [comment]
Closing as resolved, can no longer replicate the issues in this thread. However, case is a difficult topic and it's most likely that it'll be removed altogether to avoid future issues.
