### ISSUE TITLE
If count is undefined then also it goes to pluralize.plural in the current implementation.

### ISSUE THREAD

**Issue by kaushik143** [blakeembrey/pluralize#80]
In the current implementation of pluralize method:

  function pluralize (word, count, inclusive) {
    var pluralized = count === 1
      ? pluralize.singular(word) : pluralize.plural(word);

    return (inclusive ? count + ' ' : '') + pluralized;
  }

count === undefined is not handled.

Will it be good idea to have additional check for this?

**Comment by blakeembrey** [comment]
What would you expect to happen if `count` is undefined? Why would someone do this instead of adhering to the API? I'm going to avoid handling this since technically a lot of invalid inputs can occur and I'd prefer to state the expected contract upfront.

**Comment by kaushik143** [comment]
I expect if count is undefined then it should throw error: like count is undefined. So that user will know the problem.
