### ISSUE TITLE
Pluralize and performance

### ISSUE THREAD

**Issue by carpben** [blakeembrey/pluralize#96]
Thanks for this important library. I was surprised to read 
"For applications where the word(s) are known ahead of time, you can use a simple ternary (or function) which would be a much lighter alternative." 
I'd expect such a library to be very light on performance. Isn't it the case? 
Thanks in advance!

**Comment by blakeembrey** [comment]
A ternary will always be quicker than a bunch of regexp tests. However, this is not just about performance but about library weight (e.g. [2kb](https://bundlephobia.com/result?p=pluralize@7.0.0)) and accuracy. If you know the plurals you want to use in advance, there's doesn't seem to be a need to add this as a dependency.

**Comment by carpben** [comment]
At the moment there are only 2 strings which needs to be pluralized, and we know them in advance. But we do inject these fields from the back-end, and we try to keep our front-end app somewhat independent, and hide the specific details from it. So in our React App we simply have a general variable, and though it can only get 2 specific values from the back-end, it will be a bit strange to treat it as a general string all along, and then to pluralize it by handling only the two specific cases.

**Comment by blakeembrey** [comment]
I'm not really sure I follow, but you're welcome to do it whichever way you prefer. I can't prescribe how you build your front-end, but a ternary is certainly faster and lighter weight than using a library. With that said, it's unlikely you'll notice a difference in any case unless you're seriously trying to cut down on bytes in your web app (but it doesn't sound like this is the case).
